name: SizeUp

on: pull_request

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  sizeup:
    name: Estimate reviewability
    runs-on: ubuntu-latest

    steps:
      - name: Estimate pull request reviewability
        uses: lerebear/sizeup-action@f9acdbeaa4e7a79e1fa36b165f1bb68ca40d2c09
        id: sizeup-action
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          # Uncomment line below to use custom sizeup-action configuration.
          configuration-file-path: ".github/workflows/sizeup/config.yaml"
