name: SizeUp

on: pull_request

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  sizeup:
    name: Estimate reviewability
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.head.ref }}"

      - name: Estimate pull request reviewability
        uses: lerebear/sizeup-action@f4c3161f0bb5b5e110d773995ca41747d8dc7814
        id: sizeup-action
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          # Uncomment line below to use custom sizeup-action configuration.
          # configuration-file-path: ".github/workflows/sizeup/config.yaml"
