name: SizeUp

on: pull_request

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  sizeup:
    name: Run sizeup estimation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Estimate pull request reviewability
        uses: lerebear/sizeup-action@b78cb14cee18fb53035976922bd134d82cff4826
        id: sizeup-action
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-file-path: ""
