name: SizeUp

on: pull_request

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  sizeup:
    name: Estimate reviewability
    runs-on: ubuntu-latest

    steps:
      # Check out a copy of this repository so that we can compute a diff to
      # evaluate and load the Action's configuration.
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Estimate pull request reviewability
        uses: lerebear/sizeup-action@f93ba0872f47b8d2cd8642e21e1321c7c189b471
        id: sizeup-action
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
